WebBooks/WebBooks/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from catalog import views
from django.urls import *


urlpatterns = [
    path('', views.index, name='index'),
    path('authors_add/', views.authors_add, name='authors_add'),
    path('edit1/<int:id>/', views.edit1, name='edit1'),
    path('create/', views.create, name='create'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('admin/', admin.site.urls),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'account/', include('django.contrib.auth.urls')),
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    re_path(r'^book/update/(?P<pk>\d+)$', views.BookUpdate.as_view(), name='book_update'),
    re_path(r'^book/delete/(?P<pk>\d+)$', views.BookDelete.as_view(), name='book_delete'),

]

WebBooks/catalog/urls.py
from django.urls import path, re_path
from .import views
from django.http import request
from django.conf.urls import url


urlpatterns += [
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='мои заказы'),


]

WebBooks/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text='Введите жанр книги',
                            verbose_name='Жанр Книги')

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text='Введите язык книги',
                            verbose_name='Язык Книги')

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text='input name author',
                                  verbose_name="Имя автора")
    last_name = models.CharField(max_length=100,
                                 help_text='input surname author',
                                 verbose_name='Фамилия автора')
    date_of_birth = models.DateField(help_text='input date of birth',
                                     verbose_name='Дата рождения',
                                     null=True, blank=True)
    date_of_death = models.DateField(help_text='input date of death',
                                     verbose_name='Дата смерти',
                                     null=True, blank=True)

    def __str__(self):
        return self.last_name


class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text='input name book',
                             verbose_name='Название книги')
    genre = models.ForeignKey("Genre", on_delete=models.CASCADE,
                              help_text="Выберите жанр книги",
                              verbose_name='Жанр книги', null=True)
    language = models.ForeignKey('Language', on_delete=models.CASCADE,
                                 help_text='Выберите язык книги',
                                 verbose_name='Язык книги', null=True)
    author = models.ManyToManyField('Author', help_text='Выберите автора книги',
                                    verbose_name='Автор книги')
    summary = models.TextField(max_length=1000,
                               help_text='Введите краткое описание книги',
                               verbose_name='Аннотация книги')
    isbn = models.CharField(max_length=13, help_text='Должно содержать 13 символов',
                            verbose_name='ISBN книги')

    def __str__(self):
        return self.title

    def display_author(self):
        return ", ".join([author.last_name for author
                          in self.author.all()])

    display_author.short_description = 'Авторы'

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text='Введите статус экземпляра книги',
                            verbose_name='Статус экземпляра книги')

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE,
                             null=True)
    inv_num = models.CharField(max_length=20, null=True,
                               help_text='Введите инвентарный номер экземпляра',
                               verbose_name='Инвентарный номер')
    imprint = models.CharField(max_length=200,
                               help_text='Введите издательство и год выпуска',
                               verbose_name='Издательство')
    status = models.ForeignKey('Status', on_delete=models.CASCADE,
                               null=True, help_text='Изменить состояние экземпляра',
                               verbose_name='Статус экземпляра книги')
    due_back = models.DateField(null=True, blank=True,
                                help_text="введите конец срока статуса",
                                verbose_name='Дата окончания статуса')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 null=True, blank=True,
                                 verbose_name='Заказчик',
                                 help_text='Выберите заказчика книги')

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return '%s %s %s' % (self.inv_num, self.book, self.status)

WebBooks/catalog/forms.py
from django import forms
from datetime import date
from django.forms import ModelForm
from .models import Book


class AuthorsForm(forms.Form):
    first_name = forms.CharField(label='имя автора')
    last_name = forms.CharField(label='Фамилия автора')
    date_of_birth = forms.DateField(label='Дата рождения',
                                    initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_of_death = forms.DateField(label="Дата смерти", initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))


class BookModelForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'genre', 'language', 'author', 'summary', 'isbn']

WebBooks/catalog/views.py
from django.shortcuts import render
from django.http import *
from django.conf import settings
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AuthorsForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book


def index(request):
    num_books = Book.objects.all().count()
    num_instance = BookInstance.objects.all().count()
    num_instance_available = BookInstance.objects.filter(status__exact=2).count()
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(request, 'index.html',
                  context={'num_books': num_books,
                           'num_instance': num_instance,
                           'num_instance_available': num_instance_available,
                           'num_authors': num_authors,
                           'num_visits': num_visits,
                           }
                  )


class BookListView(generic.ListView):
    model = Book
    paginate_by = 3


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 4


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paganite_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='2').order_by('due_back')


def authors_add(request):
    author = Author.objects.all()
    authorsform = AuthorsForm()
    return render(request, 'catalog/authors_add.html',
                  {'form': authorsform,
                   'author': author})


def create(request):
    if request.method == "POST":
        author = Author()
        author.first_name = request.POST.get('first_name')
        author.last_name = request.POST.get('last_name')
        author.date_of_birth = request.POST.get('date_of_birth')
        author.date_of_death = request.POST.get('date_of_death')
        author.save()
        return HttpResponseRedirect('/authors_add/')


def delete(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect('/authors_add/')
    except Author.DoestNotExits:
        return HttpResponseNotFound('<h2> Автор не найден </h2>')


def edit1(request, id):
    author = Author.objects.get(id=id)
    if request.method == "POST":
        author.first_name = request.POST.get('first_name')
        author.last_name = request.POST.get('last_name')
        author.date_of_birth = request.POST.get('date_of_birth')
        author.date_of_death = request.POST.get('date_of_death')
        author.save()
        return HttpResponseRedirect('/authors_add/')
    else:
        return render(request, 'edit1.html', {"author": author})


class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')


class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')


class BookDelete(DeleteView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')

WebBooks/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Список авторов в БД</h1>
{% if author_list %}
{% for author in author_list.all %}
<p> {{ author.first_name}} {{author.last_name}},
    <strong> Родился-</strong>{{author.date_of_birth}},
    <strong> Умер-</strong>{{author.date_of_death}}
</p>
{%endfor%}
{%else%}
    <p>В БД нет авторов</p>
{% endif %}
{% endblock %}

WebBooks/catalog/templates/catalog/authors_add.html
{% extends 'base_generic.html' %}

{% block content %}

<h3> Список авторов в БД </h3>
<table>
    <thead>

    <th>ID</th>
    <th>---ИМЯ---</th>
    <th>Фамилия</th>
    <th></th>

    </thead>

    {% if author %}

    {% for author in author.all %}
    <tr>
        <td>{{ author.id }}</td>
        <td>{{ author.first_name }}</td>
        <td>{{ author.last_name }}</td>
        <td><a href="/edit1/{{ author.id }}">Изменить</a>,
            <a href="/delete/{{ author.id }}">Удалить</a></td>
    </tr>
    {% endfor %}

    {% else %}
    <p> В базе данных нет авторов</p>
    {% endif %}
</table>

<h3>Добавить в БД автора книги</h3>
<form method="post" action="/create/">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

WebBooks/catalog/templates/catalog/book_confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}

<h1>Удаление книги</h1>
<p>Уверен что хош удалить книгу: {{ book }} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" action="" value="Да, удалить" />

</form>

{% endblock %}

WebBooks/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Название кинги: {{ book.title }}</h1>

<p><strong> Жанр: </strong>  {{ book.genre  }}</p>
<p><strong> Аннотация </strong>  {{ book.summary  }}</p>
<p><strong> ISBN </strong>  {{ book.isbn  }}</p>
<p><strong> Язык </strong>  {{ book.language  }}</p>
    {% for author in book.author.all %}
    <p><strong> Автор: </strong>
        <a href="">{{ author.first_name }}
                    {{ author.last_name}}</a></p>
    {% endfor %}

<div style="margin-left:20px; margin-top:20px">
    <h4>Количество экзмпляров книг в БД</h4>
    {% for copy in book.bookinstance_set.all %}
        <hr><p class="{% if copy.status == '1' %} text-success
               {% elif copy.status == '2' %} text-danger
               {% else %} text-warning
               {% endif %}"> {{copy.get_status_display}} </p>
    <p><strong>Издательство: </strong>{{copy.imprint}}</p>
    <p class="text-muted"><strong>Инвентарный номер: </strong>{{ copy.id }}</p>
    <p><strong>Статус экземпляра книги в БД: </strong>{{ copy.status }}</p>
    {% endfor %}
</div>
{% endblock %}
<p><strong>Автор: </strong><a href="">
    {{ author.first_name }}
    {{ author.last_name }}
</a></p>

WebBooks/catalog/templates/catalog/book_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Сохранить" />

</form>

{% endblock %}

WebBooks/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Список книг в БД</h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{book.get_absolute_url}}">
            {{ book.title }}</a>
        ({{book.genre}})
        <a href="/book/update/{{ book.id }}"> Изменить</a>,
        <a href="/book/delete/{{book.id}}"> Удалить </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p> В БД нет книг</p>
{% endif %}


{% endblock %}

WebBooks/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'base_generic.html' %}

{% block content %}

    <h1> Взятые книги </h1>

    {% if  bookinstance_list %}

    <ul>

        {% for bookinst in bookinstance_list %}

      <li class="{% if bookinst.is_overdue %}
                                   text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">
                                {{bookinst.book.title}}</a>
                         ({{ bookinst.due_back }})
        </li>
        {% endfor %}

    </ul>
    {% else %}
<p> Нет книг со статумсом в заказе </p>
    {% endif %}
{% endblock %}